Use RCLCPP_VERSION_GTE from rclcpp/version.h in generic_client.cpp (#344)
### Changelog
Use RCLCPP_VERSION_GTE from rclcpp/version.h in `generic_client.cpp`

### Docs

<!-- Link to a Docs PR, tracking ticket in Linear, OR write "None" if no
documentation changes are needed. -->

### Description

The custom version of RCLCPP_VERSION_GTE was added in this commit:
https://github.com/foxglove/ros-foxglove-bridge/commit/9d920682c4b997a1e7546b5ca09f26f9daa3b940

In my build environment, the corresponding definitions conflict with the
definitions from roscpp/version.h included in parameter_interface.cpp,
added here:
https://github.com/foxglove/ros-foxglove-bridge/commit/05f362ab858c90358932d8fec07a19848e0e3884

```
| In file included from /data/yocto-styhead/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/foxglove-bridge/0.8.2-1/git/ros2_foxglove_bridge/src/parameter_interface.cpp:5:
| /data/yocto-styhead/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/foxglove-bridge/0.8.2-1/recipe-sysroot/usr/include/rclcpp/rclcpp/version.h:20:9: error: "RCLCPP_VERSION_MAJOR" redefined [-Werror]
|    20 | #define RCLCPP_VERSION_MAJOR (28)
|       |         ^~~~~~~~~~~~~~~~~~~~
| <command-line>: note: this is the location of the previous definition
| /data/yocto-styhead/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/foxglove-bridge/0.8.2-1/recipe-sysroot/usr/include/rclcpp/rclcpp/version.h:24:9: error: "RCLCPP_VERSION_MINOR" redefined [-Werror]
|    24 | #define RCLCPP_VERSION_MINOR (1)
|       |         ^~~~~~~~~~~~~~~~~~~~
| <command-line>: note: this is the location of the previous definition
| /data/yocto-styhead/build/tmp/work/cortexa9t2hf-neon-poky-linux-gnueabi/foxglove-bridge/0.8.2-1/recipe-sysroot/usr/include/rclcpp/rclcpp/version.h:28:9: error: "RCLCPP_VERSION_PATCH" redefined [-Werror]
|    28 | #define RCLCPP_VERSION_PATCH (6)
|       |         ^~~~~~~~~~~~~~~~~~~~
| <command-line>: note: this is the location of the previous definition
```

Using the definitions from `version.h` directly resolve the build error.
Is there a reason not to use the version from rclcpp?

I have not tested the changes runtime, but the build succeeds.